/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package help.view;

import help.dao.CategoriaDAO;
import help.dao.ChamadoDAO;
import help.dao.UsuarioDAO;
import help.model.Usuario;
import help.model.Chamado;
import java.sql.Date;
import java.sql.Timestamp;
/**
 *
 * @author erick
 */
public class ChamadoFrame extends javax.swing.JFrame {

    private Usuario usuario = new Usuario();
    private Chamado chamado = new Chamado();
    private CategoriaDAO categoriaDao = new CategoriaDAO();
    private ChamadoDAO chamadoDao = new ChamadoDAO();
    private UsuarioDAO usuarioDao = new UsuarioDAO();
    private HomeAnalista homeAnalista = null;
    public ChamadoFrame() {
        initComponents();
    }
    public void atualizaChamado(){
        LabelTitulo.setText(this.chamado.getTitulo());
        LabelDescricao.setText("<html><body>"+this.chamado.getCorpo()+"</body></html>");
        LabelCategoria.setText(categoriaDao.consultarCategoria(this.chamado.getIdCategoria()).getNome());
        LabelCliente.setText(usuarioDao.consultarUsuario(this.chamado.getIdUsuario()).getNome());
        LabelUrgencia.setText(this.chamado.getUrgencia());
        LabelDataCriacao.setText(chamadoDao.timeStamptoString(this.chamado.getDataCriacao()));
        TextAreaResposta.setText(this.chamado.getResposta());
        if(this.usuario.isAnalista()){
            BtnFinalizarAtendimento.setVisible(true);
            BtnIniciarAtendimento.setVisible(true);
            TextAreaResposta.setEnabled(true);
            LabelResposta.setText("Cadastrar Resposta");
        }else{
            BtnFinalizarAtendimento.setVisible(false);
            BtnIniciarAtendimento.setVisible(false);
            TextAreaResposta.setEnabled(false);
            LabelResposta.setText("Resposta Cadastrada:");
        }
        if(this.chamado.getIdAnalista() != 0)
            LabelAnalista.setText(usuarioDao.consultarUsuario(this.chamado.getIdAnalista()).getNome());
        switch(this.chamado.getStatus()){
            case 0:
                LabelDataFinalizacao.setText("Atendimento não iniciado!");
                BtnIniciarAtendimento.setEnabled(true);
                TextAreaResposta.setEnabled(false);
                BtnFinalizarAtendimento.setEnabled(false);
                break;
            case 1:
                LabelDataFinalizacao.setText("Em atendimento!");
                BtnIniciarAtendimento.setEnabled(false);
                TextAreaResposta.setEnabled(true);
                BtnFinalizarAtendimento.setEnabled(true);
                break;
            case 2:
                TextAreaResposta.setEnabled(false);
                BtnFinalizarAtendimento.setEnabled(false);
                BtnIniciarAtendimento.setEnabled(false);
                TextAreaResposta.setText(this.chamado.getResposta());
                LabelDataFinalizacao.setText(chamadoDao.timeStamptoString(this.chamado.getDataFinalizacao()));
                LabelResposta.setText("Resposta Cadastrada:");
                break;
        }
    }
    public void inicializaTela(Usuario usuario, Chamado chamado, HomeAnalista homeAnalista){
        this.usuario = usuario;
        this.chamado = chamado;
        this.homeAnalista = homeAnalista;
        atualizaChamado();
        pack();
        setLocationRelativeTo(null);
        setVisible(true);
    }
     public void inicializaTela(Usuario usuario, Chamado chamado){
        this.usuario = usuario;
        this.chamado = chamado;
        atualizaChamado();
        pack();
        setLocationRelativeTo(null);
        setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        LabelTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PanelDescricao = new javax.swing.JPanel();
        LabelDescricao = new javax.swing.JLabel();
        TextCliente = new javax.swing.JLabel();
        PanelCliente = new javax.swing.JPanel();
        LabelCliente = new javax.swing.JLabel();
        TextCategoria = new javax.swing.JLabel();
        PanelCategoria = new javax.swing.JPanel();
        LabelCategoria = new javax.swing.JLabel();
        TextUrgencia = new javax.swing.JLabel();
        PanelUrgencia = new javax.swing.JPanel();
        LabelUrgencia = new javax.swing.JLabel();
        TextAnalista = new javax.swing.JLabel();
        PanelAnalista = new javax.swing.JPanel();
        LabelAnalista = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LabelDataCriacao = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        LabelDataFinalizacao = new javax.swing.JLabel();
        BtnIniciarAtendimento = new javax.swing.JButton();
        LabelResposta = new javax.swing.JLabel();
        BtnFinalizarAtendimento = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextAreaResposta = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Chamado");

        jLabel1.setText("Titulo:");

        jPanel1.setBackground(new java.awt.Color(156, 173, 251));

        LabelTitulo.setBackground(new java.awt.Color(66, 150, 255));
        LabelTitulo.setText("Label Titulo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setText("Descrição:");

        PanelDescricao.setBackground(new java.awt.Color(156, 173, 251));

        LabelDescricao.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelDescricao.setText("Label Descrição");
        LabelDescricao.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout PanelDescricaoLayout = new javax.swing.GroupLayout(PanelDescricao);
        PanelDescricao.setLayout(PanelDescricaoLayout);
        PanelDescricaoLayout.setHorizontalGroup(
            PanelDescricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDescricaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelDescricaoLayout.setVerticalGroup(
            PanelDescricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDescricaoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );

        TextCliente.setText("Cliente:");

        PanelCliente.setBackground(new java.awt.Color(156, 173, 251));

        LabelCliente.setText("Label Cliente");

        javax.swing.GroupLayout PanelClienteLayout = new javax.swing.GroupLayout(PanelCliente);
        PanelCliente.setLayout(PanelClienteLayout);
        PanelClienteLayout.setHorizontalGroup(
            PanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
        );
        PanelClienteLayout.setVerticalGroup(
            PanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        TextCategoria.setText("Categoria:");

        PanelCategoria.setBackground(new java.awt.Color(156, 173, 251));

        LabelCategoria.setText("Label Categoria");

        javax.swing.GroupLayout PanelCategoriaLayout = new javax.swing.GroupLayout(PanelCategoria);
        PanelCategoria.setLayout(PanelCategoriaLayout);
        PanelCategoriaLayout.setHorizontalGroup(
            PanelCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCategoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelCategoriaLayout.setVerticalGroup(
            PanelCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCategoriaLayout.createSequentialGroup()
                .addComponent(LabelCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        TextUrgencia.setText("Urgencia:");

        PanelUrgencia.setBackground(new java.awt.Color(156, 173, 251));

        LabelUrgencia.setText("Label Urgencia");

        javax.swing.GroupLayout PanelUrgenciaLayout = new javax.swing.GroupLayout(PanelUrgencia);
        PanelUrgencia.setLayout(PanelUrgenciaLayout);
        PanelUrgenciaLayout.setHorizontalGroup(
            PanelUrgenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUrgenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelUrgencia, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelUrgenciaLayout.setVerticalGroup(
            PanelUrgenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelUrgencia, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
        );

        TextAnalista.setText("Analista:");

        PanelAnalista.setBackground(new java.awt.Color(156, 173, 251));

        LabelAnalista.setText("Não Atribuido!");

        javax.swing.GroupLayout PanelAnalistaLayout = new javax.swing.GroupLayout(PanelAnalista);
        PanelAnalista.setLayout(PanelAnalistaLayout);
        PanelAnalistaLayout.setHorizontalGroup(
            PanelAnalistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAnalistaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelAnalista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelAnalistaLayout.setVerticalGroup(
            PanelAnalistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelAnalista, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
        );

        jLabel3.setText("Data de Criação:");

        LabelDataCriacao.setText("Label Data de Criação");

        jLabel4.setText("Data de Finalização:");

        LabelDataFinalizacao.setText("Não Finalizado!");

        BtnIniciarAtendimento.setText("Iniciar Atendimento");
        BtnIniciarAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIniciarAtendimentoActionPerformed(evt);
            }
        });

        LabelResposta.setText("Cadastrar Resposta:");

        BtnFinalizarAtendimento.setText("Finalizar Atendimento");
        BtnFinalizarAtendimento.setEnabled(false);
        BtnFinalizarAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFinalizarAtendimentoActionPerformed(evt);
            }
        });

        TextAreaResposta.setColumns(20);
        TextAreaResposta.setRows(5);
        jScrollPane1.setViewportView(TextAreaResposta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnFinalizarAtendimento)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(LabelDataCriacao)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(PanelDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(238, 238, 238)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(LabelDataFinalizacao)
                                    .addComponent(BtnIniciarAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TextCliente)
                                            .addComponent(PanelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(TextCategoria)
                                                .addGap(106, 120, Short.MAX_VALUE))
                                            .addComponent(PanelCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TextUrgencia)
                                            .addComponent(PanelUrgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(TextAnalista)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(PanelAnalista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                    .addComponent(LabelResposta, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(BtnIniciarAtendimento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelDataCriacao)
                            .addComponent(LabelDataFinalizacao))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(PanelCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TextCliente)
                                    .addComponent(TextCategoria))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PanelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TextAnalista)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PanelAnalista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TextUrgencia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PanelUrgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(LabelResposta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnFinalizarAtendimento)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnIniciarAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIniciarAtendimentoActionPerformed
        // TODO add your handling code here:
        this.chamado.setStatus(1);
        this.chamado.setIdAnalista(this.usuario.getId());
        chamadoDao.iniciarAtendimento(this.chamado.getId(), this.usuario.getId());
        atualizaChamado();
        this.homeAnalista.carregarTabela();
    }//GEN-LAST:event_BtnIniciarAtendimentoActionPerformed

    private void BtnFinalizarAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFinalizarAtendimentoActionPerformed
        // TODO add your handling code here:
        String resposta = TextAreaResposta.getText();
        this.chamado.setStatus(2);
        chamadoDao.finalizarAtendimento(this.chamado.getId(), resposta);
        this.chamado.setDataFinalizacao(new Timestamp(new java.util.Date().getTime()));
        atualizaChamado();
        this.homeAnalista.carregarTabela();
    }//GEN-LAST:event_BtnFinalizarAtendimentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChamadoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnFinalizarAtendimento;
    private javax.swing.JButton BtnIniciarAtendimento;
    private javax.swing.JLabel LabelAnalista;
    private javax.swing.JLabel LabelCategoria;
    private javax.swing.JLabel LabelCliente;
    private javax.swing.JLabel LabelDataCriacao;
    private javax.swing.JLabel LabelDataFinalizacao;
    private javax.swing.JLabel LabelDescricao;
    private javax.swing.JLabel LabelResposta;
    private javax.swing.JLabel LabelTitulo;
    private javax.swing.JLabel LabelUrgencia;
    private javax.swing.JPanel PanelAnalista;
    private javax.swing.JPanel PanelCategoria;
    private javax.swing.JPanel PanelCliente;
    private javax.swing.JPanel PanelDescricao;
    private javax.swing.JPanel PanelUrgencia;
    private javax.swing.JLabel TextAnalista;
    private javax.swing.JTextArea TextAreaResposta;
    private javax.swing.JLabel TextCategoria;
    private javax.swing.JLabel TextCliente;
    private javax.swing.JLabel TextUrgencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
