/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package help.view;

import help.dao.CategoriaDAO;
import help.dao.ChamadoDAO;
import help.dao.UsuarioDAO;
import help.model.Categoria;
import help.model.Chamado;
import help.model.Filtro;
import help.model.Usuario;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author erick
 */
public class HomeAnalista extends javax.swing.JFrame {

    /**
     * Creates new form HomeAnalista
     */
    private Usuario usuario = new Usuario();
    private ChamadoDAO chamadoDao = new ChamadoDAO();
    private CategoriaDAO categoriaDao = new CategoriaDAO();
    private UsuarioDAO usuarioDao = new UsuarioDAO();
    private Filtro filtro = new Filtro();
    private Login login = null;
    private ChamadoFrame chamadoFrame = new ChamadoFrame();
    public HomeAnalista() {
        initComponents();
        carregarTabela();
        carregarTabelaCategorias();
        carregarTabelaUsuarios();
        this.PanelFiltros.setVisible(false);
    }
    public void inicializaTela(Usuario usuarioLogado, Login login){
        setExtendedState(MAXIMIZED_BOTH); 
        pack();
        setLocationRelativeTo(null);
        setVisible(true);
        this.usuario = usuarioLogado;
        this.login = login;
        LabelUsuarioLogado.setText(this.usuario.getNome());
    }
    public void carregarTabela(){
        String[] campos = {"id","Titulo","Urgencia","Categoria", "Cliente", "Data Criacao", "Status", "Responsavel"};
        DefaultTableModel dtm = new DefaultTableModel(campos, 0);
        this.tblChamados.setModel(dtm);
        if(RadioMostrarSomenteMeusChamados.isSelected())
            this.filtro.setAnalista(this.usuario.getId());
        List<Chamado> chamados = chamadoDao.consultarChamados(this.filtro);
        
        for(Chamado c: chamados){
            Categoria cat = categoriaDao.consultarCategoria(c.getIdCategoria());
            Usuario cli = usuarioDao.consultarUsuario(c.getIdUsuario());
            Usuario analista = usuarioDao.consultarUsuario(c.getIdAnalista());
            
            String nomeAnalista = "";
            if(analista != null)
                nomeAnalista = analista.getNome();
            
            String dataCriacao = chamadoDao.timeStamptoString(c.getDataCriacao());
            String status = chamadoDao.statusToString(c.getStatus());
            String id = String.valueOf(c.getId());
            String[] valores = {id, c.getTitulo(), c.getUrgencia(),cat.getNome(), cli.getNome(), dataCriacao, status, nomeAnalista};
            dtm.addRow(valores);
        }
    }
    private void carregarTabelaCategorias(){
        String[] campos = {"id", "Nome"};
        DefaultTableModel dtm = new DefaultTableModel(campos, 0);
        this.tblCategorias.setModel(dtm);
        List<Categoria> categorias = categoriaDao.consultarCategorias();
        for(Categoria c: categorias){
            String id = String.valueOf(c.getId());
            String[] valores = {id, c.getNome()};
            dtm.addRow(valores);
        }
    }
    private void carregarTabelaUsuarios(){
        String[] campos = {"id", "Nome", "Email","Tipo"};
        DefaultTableModel dtm = new DefaultTableModel(campos, 0);
        this.tblUsuarios.setModel(dtm);
        List<Usuario> usuarios = usuarioDao.consultarUsuarios();
        for(Usuario u: usuarios){
            String id = String.valueOf(u.getId());
            String tipo;
            if(u.isAnalista())
                tipo = "Analista";
            else
                tipo = "Cliente";
            String[] valores = {id, u.getNome(), u.getEmail(), tipo};
            dtm.addRow(valores);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        LabelUsuarioLogado = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblChamados = new javax.swing.JTable();
        RadioMostrarSomenteMeusChamados = new javax.swing.JRadioButton();
        btnExibirFiltros = new javax.swing.JButton();
        PanelFiltros = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbFiltroClientes = new javax.swing.JComboBox<>();
        cbFiltroCategorias = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btnFiltrar = new javax.swing.JButton();
        btnFecharFiltros = new javax.swing.JButton();
        RadioMostrarFinalizados = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCategorias = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        TextFieldNomeCategoria = new javax.swing.JTextField();
        BtnCadastrarCategoria = new javax.swing.JButton();
        BtnRemoverCategoria = new javax.swing.JButton();
        TextFieldIdCategoria = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        TextFieldNomeUsuario = new javax.swing.JTextField();
        BtnCadastrarUsuario = new javax.swing.JButton();
        BtnRemoverUsuario = new javax.swing.JButton();
        TextFieldIdUsuario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TextFieldEmailUsuario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        FieldSenhaUsuario = new javax.swing.JPasswordField();
        FieldConfirmarSenha = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ComboBoxAnalista = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Painel do Analista");
        setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jLabel2.setText("Usuario Logado:");

        LabelUsuarioLogado.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        LabelUsuarioLogado.setText("Usuario");

        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane1.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N

        tblChamados.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        tblChamados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Titulo", "Urgencia", "Categoria", "Cliente", "Data Criacao", "Status", "Responsavel"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblChamados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblChamadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblChamados);
        if (tblChamados.getColumnModel().getColumnCount() > 0) {
            tblChamados.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        RadioMostrarSomenteMeusChamados.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        RadioMostrarSomenteMeusChamados.setText("Mostrar Apenas meus Chamados");
        RadioMostrarSomenteMeusChamados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioMostrarSomenteMeusChamadosActionPerformed(evt);
            }
        });

        btnExibirFiltros.setText("Exibir Filtros");
        btnExibirFiltros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExibirFiltrosActionPerformed(evt);
            }
        });

        PanelFiltros.setBackground(new java.awt.Color(158, 158, 158));
        PanelFiltros.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Cliente:");

        cbFiltroClientes.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        cbFiltroClientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Qualquer" }));
        cbFiltroClientes.setToolTipText("");
        cbFiltroClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFiltroClientesActionPerformed(evt);
            }
        });

        cbFiltroCategorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Qualquer" }));
        cbFiltroCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFiltroCategoriasActionPerformed(evt);
            }
        });

        jLabel3.setText("Categoria:");

        btnFiltrar.setText("Filtrar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });

        btnFecharFiltros.setText("X");
        btnFecharFiltros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharFiltrosActionPerformed(evt);
            }
        });

        RadioMostrarFinalizados.setText("Mostrar Finalizados");
        RadioMostrarFinalizados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioMostrarFinalizadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelFiltrosLayout = new javax.swing.GroupLayout(PanelFiltros);
        PanelFiltros.setLayout(PanelFiltrosLayout);
        PanelFiltrosLayout.setHorizontalGroup(
            PanelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFiltrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelFiltrosLayout.createSequentialGroup()
                        .addGroup(PanelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbFiltroClientes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbFiltroCategorias, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelFiltrosLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFecharFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelFiltrosLayout.createSequentialGroup()
                        .addComponent(RadioMostrarFinalizados)
                        .addGap(0, 28, Short.MAX_VALUE))))
        );
        PanelFiltrosLayout.setVerticalGroup(
            PanelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFiltrosLayout.createSequentialGroup()
                .addGroup(PanelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(btnFecharFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbFiltroClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbFiltroCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(RadioMostrarFinalizados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFiltrar)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(RadioMostrarSomenteMeusChamados)
                        .addGap(0, 1189, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(btnExibirFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(LabelUsuarioLogado))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RadioMostrarSomenteMeusChamados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 819, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelUsuarioLogado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(btnExibirFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Chamados", jPanel1);

        tblCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCategorias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCategoriasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblCategorias);
        if (tblCategorias.getColumnModel().getColumnCount() > 0) {
            tblCategorias.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        jLabel4.setText("Id");

        TextFieldNomeCategoria.setText("Nome da Categoria");
        TextFieldNomeCategoria.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextFieldNomeCategoriaFocusGained(evt);
            }
        });
        TextFieldNomeCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldNomeCategoriaActionPerformed(evt);
            }
        });

        BtnCadastrarCategoria.setText("Cadastrar");
        BtnCadastrarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCadastrarCategoriaActionPerformed(evt);
            }
        });

        BtnRemoverCategoria.setText("Remover");
        BtnRemoverCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRemoverCategoriaActionPerformed(evt);
            }
        });

        TextFieldIdCategoria.setText("Id");
        TextFieldIdCategoria.setEnabled(false);
        TextFieldIdCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldIdCategoriaActionPerformed(evt);
            }
        });

        jLabel5.setText("Nome");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(333, 333, 333)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(121, 121, 121))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(TextFieldIdCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(BtnCadastrarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BtnRemoverCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(TextFieldNomeCategoria, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(334, 334, 334))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextFieldIdCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextFieldNomeCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnCadastrarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnRemoverCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(161, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Categorias", jPanel2);

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Nome", "Email", "Analista"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsuariosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblUsuarios);
        if (tblUsuarios.getColumnModel().getColumnCount() > 0) {
            tblUsuarios.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        jLabel6.setText("Id");

        TextFieldNomeUsuario.setText("Nome do Usuario");
        TextFieldNomeUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextFieldNomeUsuarioFocusGained(evt);
            }
        });
        TextFieldNomeUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldNomeUsuarioActionPerformed(evt);
            }
        });

        BtnCadastrarUsuario.setText("Cadastrar");
        BtnCadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCadastrarUsuarioActionPerformed(evt);
            }
        });

        BtnRemoverUsuario.setText("Remover");
        BtnRemoverUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRemoverUsuarioActionPerformed(evt);
            }
        });

        TextFieldIdUsuario.setText("Id");
        TextFieldIdUsuario.setEnabled(false);
        TextFieldIdUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldIdUsuarioActionPerformed(evt);
            }
        });

        jLabel7.setText("Nome");

        TextFieldEmailUsuario.setText("Endereço de Email");
        TextFieldEmailUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextFieldEmailUsuarioFocusGained(evt);
            }
        });
        TextFieldEmailUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldEmailUsuarioActionPerformed(evt);
            }
        });

        jLabel8.setText("Email:");

        jLabel9.setText("Senha:");

        FieldSenhaUsuario.setText("jPasswordField1");
        FieldSenhaUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FieldSenhaUsuarioFocusGained(evt);
            }
        });

        FieldConfirmarSenha.setText("jPasswordField1");
        FieldConfirmarSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FieldConfirmarSenhaFocusGained(evt);
            }
        });

        jLabel10.setText("Confirmar Senha:");

        jLabel11.setText("Tipo");

        ComboBoxAnalista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Analista" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(278, 278, 278)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(TextFieldIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 358, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(BtnCadastrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                                .addComponent(BtnRemoverUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(TextFieldNomeUsuario)
                            .addComponent(TextFieldEmailUsuario)
                            .addComponent(FieldSenhaUsuario)
                            .addComponent(FieldConfirmarSenha)
                            .addComponent(ComboBoxAnalista, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(241, 241, 241))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextFieldIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextFieldNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextFieldEmailUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FieldSenhaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FieldConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComboBoxAnalista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnCadastrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnRemoverUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(161, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Usuarios", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        login.Logout();
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void RadioMostrarSomenteMeusChamadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioMostrarSomenteMeusChamadosActionPerformed
        // TODO add your handling code here:
        if(RadioMostrarSomenteMeusChamados.isSelected()){
            carregarTabela();
        }else{
            this.filtro.setAnalista(0);
            carregarTabela();
        }
    }//GEN-LAST:event_RadioMostrarSomenteMeusChamadosActionPerformed

    private void cbFiltroCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFiltroCategoriasActionPerformed
        // TODO add your handling code here:
        String categoria = (String)this.cbFiltroCategorias.getSelectedItem();
        if(categoria.equals("Qualquer"))
            this.filtro.setCategoria(0);
        else
            this.filtro.setCategoria(categoriaDao.consultarCategoriaNome(categoria).getId());
        carregarTabela();
    }//GEN-LAST:event_cbFiltroCategoriasActionPerformed

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        // TODO add your handling code here:
        String cliente = (String)this.cbFiltroClientes.getSelectedItem();
        String categoria = (String)this.cbFiltroCategorias.getSelectedItem();
        if(cliente.equals("Qualquer"))
            this.filtro.setUsuario(0);
        else
            this.filtro.setUsuario(usuarioDao.consultarUsuarioNome(cliente).getId());
        if(categoria.equals("Qualquer"))
            this.filtro.setCategoria(0);
        else
            this.filtro.setCategoria(categoriaDao.consultarCategoriaNome(categoria).getId());
        carregarTabela();
    }//GEN-LAST:event_btnFiltrarActionPerformed

    private void btnExibirFiltrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExibirFiltrosActionPerformed
        // TODO add your handling code here:
        List<Categoria> categorias = categoriaDao.consultarCategorias();
        for(Categoria cat: categorias){
            this.cbFiltroCategorias.addItem(cat.getNome());
        }
        List<Usuario> clientes = usuarioDao.consultarUsuariosClientes();
        for(Usuario cli: clientes){
            this.cbFiltroClientes.addItem(cli.getNome());
        }
        this.PanelFiltros.setVisible(true);
    }//GEN-LAST:event_btnExibirFiltrosActionPerformed

    private void btnFecharFiltrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharFiltrosActionPerformed
        // TODO add your handling code here:
        this.PanelFiltros.setVisible(false);
    }//GEN-LAST:event_btnFecharFiltrosActionPerformed

    private void cbFiltroClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFiltroClientesActionPerformed
        // TODO add your handling code here:
        String cliente = (String)this.cbFiltroClientes.getSelectedItem();
        if(cliente.equals("Qualquer"))
            this.filtro.setUsuario(0);
        else
            this.filtro.setUsuario(usuarioDao.consultarUsuarioNome(cliente).getId());
        carregarTabela();
    }//GEN-LAST:event_cbFiltroClientesActionPerformed

    private void RadioMostrarFinalizadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioMostrarFinalizadosActionPerformed
        // TODO add your handling code here:
        if(RadioMostrarFinalizados.isSelected())
            this.filtro.setMostrarFinalizados(true);
        else
            this.filtro.setMostrarFinalizados(false);  
        carregarTabela();
            
    }//GEN-LAST:event_RadioMostrarFinalizadosActionPerformed

    private void tblChamadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChamadosMouseClicked
        // TODO add your handling code here:
        int coluna = 0;
        int linha = tblChamados.getSelectedRow();
        int id = Integer.parseInt(tblChamados.getModel().getValueAt(linha, coluna).toString());
        Chamado chamado = chamadoDao.consultarChamado(id);
        chamadoFrame.inicializaTela(this.usuario, chamado, this);
    }//GEN-LAST:event_tblChamadosMouseClicked

    private void TextFieldNomeCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldNomeCategoriaActionPerformed
        // TODO add your handling code here:
        TextFieldNomeCategoria.setText("");
    }//GEN-LAST:event_TextFieldNomeCategoriaActionPerformed

    private void BtnCadastrarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCadastrarCategoriaActionPerformed
        // TODO add your handling code here:
        String nome = TextFieldNomeCategoria.getText();
        String id = TextFieldIdCategoria.getText();
        if(id.equals("Id")){
            categoriaDao.inserirCategoria(new Categoria(nome));
            TextFieldIdCategoria.setText("Id");
            TextFieldNomeCategoria.setText("Nome da Categoria");
        }else{
            categoriaDao.atualizarCategoria(new Categoria(nome, Integer.parseInt(id)));
            TextFieldIdCategoria.setText("Id");
            TextFieldNomeCategoria.setText("Nome da Categoria");
        }
        carregarTabelaCategorias();
    }//GEN-LAST:event_BtnCadastrarCategoriaActionPerformed

    private void TextFieldIdCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldIdCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldIdCategoriaActionPerformed

    private void TextFieldNomeCategoriaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextFieldNomeCategoriaFocusGained
        // TODO add your handling code here:
        TextFieldNomeCategoria.selectAll();
    }//GEN-LAST:event_TextFieldNomeCategoriaFocusGained

    private void tblCategoriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCategoriasMouseClicked
        // TODO add your handling code here:
        int coluna = 0;
        int linha = tblCategorias.getSelectedRow();
        int id = Integer.parseInt(tblCategorias.getModel().getValueAt(linha, coluna).toString());
        Categoria categoria = categoriaDao.consultarCategoria(id);
        TextFieldIdCategoria.setText(String.valueOf(categoria.getId()));
        TextFieldNomeCategoria.setText(categoria.getNome());
        
    }//GEN-LAST:event_tblCategoriasMouseClicked

    private void BtnRemoverCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRemoverCategoriaActionPerformed
        // TODO add your handling code here:
        String id = TextFieldIdCategoria.getText();
        categoriaDao.removerCategoria(Integer.parseInt(id));
        TextFieldIdCategoria.setText("Id");
        TextFieldNomeCategoria.setText("Nome da Categoria");
        carregarTabelaCategorias();
    }//GEN-LAST:event_BtnRemoverCategoriaActionPerformed

    private void tblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuariosMouseClicked
        // TODO add your handling code here:
        int coluna = 0;
        int linha = tblUsuarios.getSelectedRow();
        int id = Integer.parseInt(tblUsuarios.getModel().getValueAt(linha, coluna).toString());
        Usuario usuario = usuarioDao.consultarUsuario(id);
        TextFieldIdUsuario.setText(String.valueOf(usuario.getId()));
        TextFieldNomeUsuario.setText(usuario.getNome());
        TextFieldEmailUsuario.setText(usuario.getEmail());
        FieldSenhaUsuario.setText(usuario.getSenha());
        FieldConfirmarSenha.setText(usuario.getSenha());
        if(usuario.isAnalista())
            ComboBoxAnalista.setSelectedIndex(1);
        else
            ComboBoxAnalista.setSelectedIndex(0);
    }//GEN-LAST:event_tblUsuariosMouseClicked

    private void TextFieldNomeUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextFieldNomeUsuarioFocusGained
        // TODO add your handling code here:
        TextFieldNomeUsuario.selectAll();
    }//GEN-LAST:event_TextFieldNomeUsuarioFocusGained

    private void TextFieldNomeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldNomeUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldNomeUsuarioActionPerformed

    private void BtnCadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCadastrarUsuarioActionPerformed
        // TODO add your handling code here:
        String nome = TextFieldNomeUsuario.getText();
        String id = TextFieldIdUsuario.getText();
        String email = TextFieldEmailUsuario.getText();
        String senha = FieldSenhaUsuario.getText();
        String confirmar = FieldConfirmarSenha.getText();
        int analista = ComboBoxAnalista.getSelectedIndex();    
        Boolean isAnalista;
        isAnalista = analista != 0;
        if(senha.equals(confirmar)){
            if(id.equals("Id")){
                usuarioDao.inserirUsuario(new Usuario(nome, email, senha, isAnalista));
                TextFieldIdUsuario.setText("Id");
                TextFieldNomeUsuario.setText("Nome do Usuario");
                TextFieldEmailUsuario.setText("Email do Usuario");
            }else{
                usuarioDao.atualizarUsuario(new Usuario(Integer.parseInt(id),nome, email, senha, isAnalista));
                TextFieldIdUsuario.setText("Id");
                TextFieldNomeUsuario.setText("Nome do Usuario");
                TextFieldEmailUsuario.setText("Email do Usuario");
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "As senhas diferem!");
        }
        
        carregarTabelaUsuarios();
    }//GEN-LAST:event_BtnCadastrarUsuarioActionPerformed

    private void BtnRemoverUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRemoverUsuarioActionPerformed
        // TODO add your handling code here:
        String id = TextFieldIdUsuario.getText();
        usuarioDao.removerUsuario(Integer.parseInt(id));
        TextFieldIdUsuario.setText("Id");
        TextFieldNomeUsuario.setText("Nome do Usuario");
        TextFieldEmailUsuario.setText("Email do Usuario");
        carregarTabelaUsuarios();
    }//GEN-LAST:event_BtnRemoverUsuarioActionPerformed

    private void TextFieldIdUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldIdUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldIdUsuarioActionPerformed

    private void TextFieldEmailUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextFieldEmailUsuarioFocusGained
        // TODO add your handling code here:
        TextFieldEmailUsuario.selectAll();
    }//GEN-LAST:event_TextFieldEmailUsuarioFocusGained

    private void TextFieldEmailUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldEmailUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldEmailUsuarioActionPerformed

    private void FieldSenhaUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FieldSenhaUsuarioFocusGained
        // TODO add your handling code here:
        FieldSenhaUsuario.selectAll();
    }//GEN-LAST:event_FieldSenhaUsuarioFocusGained

    private void FieldConfirmarSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FieldConfirmarSenhaFocusGained
        // TODO add your handling code here:
        FieldConfirmarSenha.selectAll();
    }//GEN-LAST:event_FieldConfirmarSenhaFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeAnalista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeAnalista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeAnalista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeAnalista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeAnalista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCadastrarCategoria;
    private javax.swing.JButton BtnCadastrarUsuario;
    private javax.swing.JButton BtnRemoverCategoria;
    private javax.swing.JButton BtnRemoverUsuario;
    private javax.swing.JComboBox<String> ComboBoxAnalista;
    private javax.swing.JPasswordField FieldConfirmarSenha;
    private javax.swing.JPasswordField FieldSenhaUsuario;
    private javax.swing.JLabel LabelUsuarioLogado;
    private javax.swing.JPanel PanelFiltros;
    private javax.swing.JRadioButton RadioMostrarFinalizados;
    private javax.swing.JRadioButton RadioMostrarSomenteMeusChamados;
    private javax.swing.JTextField TextFieldEmailUsuario;
    private javax.swing.JTextField TextFieldIdCategoria;
    private javax.swing.JTextField TextFieldIdUsuario;
    private javax.swing.JTextField TextFieldNomeCategoria;
    private javax.swing.JTextField TextFieldNomeUsuario;
    private javax.swing.JButton btnExibirFiltros;
    private javax.swing.JButton btnFecharFiltros;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JComboBox<String> cbFiltroCategorias;
    private javax.swing.JComboBox<String> cbFiltroClientes;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblCategorias;
    private javax.swing.JTable tblChamados;
    private javax.swing.JTable tblUsuarios;
    // End of variables declaration//GEN-END:variables
}
