/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package help.view;

import help.dao.CategoriaDAO;
import help.dao.ChamadoDAO;
import help.dao.UsuarioDAO;
import help.model.Categoria;
import help.model.Chamado;
import help.model.Filtro;
import help.model.Usuario;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author erick
 */
public class HomeCliente extends javax.swing.JFrame {

    private Login login = null;
    private ChamadoFrame chamadoFrame = new ChamadoFrame();
    private Usuario usuario = new Usuario();
    private ChamadoDAO chamadoDao = new ChamadoDAO();
    private CategoriaDAO categoriaDao = new CategoriaDAO();
    private UsuarioDAO usuarioDao = new UsuarioDAO();
    public HomeCliente() {
        initComponents();
    }
    public void inicializaTela(Usuario usuarioLogado, Login login){
        setExtendedState(MAXIMIZED_BOTH); 
        pack();
        setLocationRelativeTo(null);
        setVisible(true); 
        this.usuario = usuarioLogado;
        this.login = login;
        LabelUsuarioLogado.setText(this.usuario.getNome());
        carregarTabela();
        carregarCategorias();
    }
    public void carregarTabela(){
        String[] campos = {"id","Titulo","Categoria","Status","Responsavel"};
        DefaultTableModel dtm = new DefaultTableModel(campos, 0);
        this.TabelaChamados.setModel(dtm);
        Filtro filtro = new Filtro();
        filtro.setUsuario(this.usuario.getId());
        filtro.mostrarFinalizados = true;
        List<Chamado> chamados = chamadoDao.consultarChamados(filtro);
        
        for(Chamado c: chamados){
            Categoria cat = categoriaDao.consultarCategoria(c.getIdCategoria());
            Usuario analista = usuarioDao.consultarUsuario(c.getIdAnalista());
            
            String nomeAnalista = "";
            if(analista != null)
                nomeAnalista = analista.getNome();
            else
                nomeAnalista = "Não Atribuido";
            String status = chamadoDao.statusToString(c.getStatus());
            String id = String.valueOf(c.getId());
            String[] valores = {id,c.getTitulo(),cat.getNome(),status, nomeAnalista};
            dtm.addRow(valores);
        }
    }
    private void carregarCategorias(){
        List<Categoria> categorias = categoriaDao.consultarCategorias();
        for(Categoria cat: categorias){
            this.ComboBoxCategoria.addItem(cat.getNome());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtnCadastrarChamado = new javax.swing.JButton();
        ComboBoxCategoria = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextAreaDescricao = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        TextFieldTitulo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaChamados = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        BtnLogout = new javax.swing.JToggleButton();
        LabelUsuarioLogado = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ComboBoxUrgencia = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(130, 35, 209));

        BtnCadastrarChamado.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        BtnCadastrarChamado.setText("Cadastrar Chamado");
        BtnCadastrarChamado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCadastrarChamadoActionPerformed(evt);
            }
        });

        ComboBoxCategoria.setBackground(new java.awt.Color(254, 254, 254));
        ComboBoxCategoria.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setText("Categoria");

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(254, 254, 254));
        jLabel6.setText("Urgencia");

        TextAreaDescricao.setBackground(new java.awt.Color(254, 254, 254));
        TextAreaDescricao.setColumns(20);
        TextAreaDescricao.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        TextAreaDescricao.setRows(5);
        jScrollPane2.setViewportView(TextAreaDescricao);

        jLabel4.setBackground(new java.awt.Color(254, 254, 254));
        jLabel4.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setText("Descrição:");

        TextFieldTitulo.setBackground(new java.awt.Color(254, 254, 254));
        TextFieldTitulo.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setText("Titulo:");

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("Cadastrar Chamado");

        TabelaChamados.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        TabelaChamados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Titulo", "Categoria", "Status", "Responsável"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaChamados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaChamadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaChamados);
        if (TabelaChamados.getColumnModel().getColumnCount() > 0) {
            TabelaChamados.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("Seus Chamados:");

        BtnLogout.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        BtnLogout.setText("Logout");
        BtnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLogoutActionPerformed(evt);
            }
        });

        LabelUsuarioLogado.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        LabelUsuarioLogado.setForeground(new java.awt.Color(254, 254, 254));
        LabelUsuarioLogado.setText("Usuario Logado");

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(254, 254, 254));
        jLabel7.setText("Logado Como:");

        ComboBoxUrgencia.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        ComboBoxUrgencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Muito Urgente", "Urgente", "Média", "Baixa" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
                        .addComponent(TextFieldTitulo))
                    .addComponent(ComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCadastrarChamado, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxUrgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 934, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LabelUsuarioLogado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addComponent(BtnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelUsuarioLogado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnLogout))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ComboBoxUrgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnCadastrarChamado, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 817, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLogoutActionPerformed
        login.Logout();
        this.usuario = new Usuario();
        setVisible(false);
    }//GEN-LAST:event_BtnLogoutActionPerformed

    private void BtnCadastrarChamadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCadastrarChamadoActionPerformed
        String titulo = this.TextFieldTitulo.getText();
        String descricao = this.TextAreaDescricao.getText();
        String urgencia = this.ComboBoxUrgencia.getSelectedItem().toString();
        String categoria = (String)this.ComboBoxCategoria.getSelectedItem();
        int categoriaId = categoriaDao.consultarCategoriaNome(categoria).getId();
        Chamado chamado = new Chamado(titulo, descricao, categoriaId, this.usuario.getId(), 0, urgencia);
        chamadoDao.inserirChamado(chamado);
        TextAreaDescricao.setText("");
        TextFieldTitulo.setText("");
        ComboBoxUrgencia.setSelectedIndex(0);
        ComboBoxCategoria.setSelectedIndex(0);
        carregarTabela();
    }//GEN-LAST:event_BtnCadastrarChamadoActionPerformed

    private void TabelaChamadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaChamadosMouseClicked
        int coluna = 0;
        int linha = TabelaChamados.getSelectedRow();
        int id = Integer.parseInt(TabelaChamados.getModel().getValueAt(linha, coluna).toString());
        Chamado chamado = chamadoDao.consultarChamado(id);
        chamadoFrame.inicializaTela(this.usuario, chamado);
    }//GEN-LAST:event_TabelaChamadosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCadastrarChamado;
    private javax.swing.JToggleButton BtnLogout;
    private javax.swing.JComboBox<String> ComboBoxCategoria;
    private javax.swing.JComboBox<String> ComboBoxUrgencia;
    private javax.swing.JLabel LabelUsuarioLogado;
    private javax.swing.JTable TabelaChamados;
    private javax.swing.JTextArea TextAreaDescricao;
    private javax.swing.JTextField TextFieldTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
